title: Isabel's Thoughts
markdown: kramdown
url: "https://isfernandez.github.io/"
#baseurl: "/jekyll-theme-material-you"

# for atom feed
author:
  name: Isabel Fernandez
  email: bel.f.pereira@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
